# Project information
site_name: DigiDocs
site_description: "DigiDocs is a collection of concise, to-the-point tutorials for technologies by Evan Tay."
site_author: "Evan Tay"
site_url: "https://www.evantay.com/docs/"

# Repository
repo_name: "DigiPie/digidocs"
repo_url: "https://github.com/DigiPie/digidocs"

# Copyright
copyright: "Copyright &copy; Evan Tay"

# Configuration
theme:
  name: "material"
  language: "en"
  custom_dir: "add"
  highlightjs: true
  feature:
    tabs: true
  palette:
    primary: "brown"
    accent: "brown"

# Customization
extra:
  social:
    - type: "github"
      link: "https://github.com/DigiPie"
    - type: "globe"
      link: "http://www.evantay.com"
  disqus: "digipie-digidocs"
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Full-Stack:
    - MongoDB:
      - Cheat-sheet: full-stack/mongodb/cheat-sheet.md
      - Local-setup: full-stack/mongodb/local-setup.md
    - NodeJS:
      - Auto-reload: full-stack/nodejs/auto-reload.md
      - Set-npm-run-shell: full-stack/nodejs/set-npm-run-shell.md
  - Git:
    - Cheat-sheet: git/cheat-sheet.md
    - Ignoring files: git/ignoring-files.md
  - Tech-Ops:
    - Docker: tech-ops/docker.md
    - Heroku-quick-deploy: tech-ops/heroku-quick-deploy.md
    - Ubuntu18-04: tech-ops/ubuntu18-04.md
  - Others:
    - C:
      - Arguments: others/c/arguments.md
    
