site_name: DigiDocs
nav:
    - Home: 'index.md'
    - DevOps:
        - Index: 'DevOps/index.md'
        - Docker: 'DevOps/Docker.md'
        - Ubuntu 18.04: 'DevOps/Ubuntu18_04.md'
    - R Basics:
        - Index: 'R/index.md'
        - Functions and data access: 'R/functions.md'
        - Vectors and Subsetting: 'R/vectors.md'
        - Sort, Order and Rank: 'R/vector_manipulation.md'
        - Data Frame and Coercion: 'R/dataframe.md'
        - Vector Arithmetic: 'R/vector_arithmetic.md'
        - Data Manipulation: 'R/data_manipulation.md'
        - Basic Plotting: 'R/basic_plotting.md'
        - R Programming: 'R/r_programming.md'
theme:
  name: 'material'
  custom_dir: 'add'
  highlightjs: true
markdown_extensions:
  - 'fenced_code'
  - 'admonition'
repo_url: 'https://github.com/DigiPie/digidocs'
copyright: 'Evan Tay'
edit_uri: ''
extra:
  social:
    - type: 'globe'
      link: 'http://www.evantay.com'
    - type: 'github-alt'
      link: 'https://github.com/DigiPie'
