# Project information
site_name: DigiDocs
site_description: 'A MkDocs powered static site for personal note-taking and documentation.'
site_author: 'Evan Tay'
site_url: 'http://digipie.github.io/'

# Repository
repo_name: 'DigiPie/digidocs'
repo_url: 'https://github.com/DigiPie/digidocs'

# Copyright
copyright: 'Copyright &copy; Evan Tay'

# Configuration
theme:
  name: 'material'
  language: 'en'
  custom_dir: 'add'
  highlightjs: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/DigiPie'
    - type: 'globe'
      link: 'http://www.evantay.com'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true

nav:
    - Home: 'index.md'
    - DevOps:
        - Index: 'DevOps/index.md'
        - Docker: 'DevOps/Docker.md'
        - Ubuntu 18.04: 'DevOps/Ubuntu18_04.md'
    - R Basics:
        - Index: 'R/index.md'
        - Functions and data access: 'R/functions.md'
        - Vectors and Subsetting: 'R/vectors.md'
        - Sort, Order and Rank: 'R/vector_manipulation.md'
        - Data Frame and Coercion: 'R/dataframe.md'
        - Vector Arithmetic: 'R/vector_arithmetic.md'
        - Data Manipulation: 'R/data_manipulation.md'
        - Basic Plotting: 'R/basic_plotting.md'
        - R Programming: 'R/r_programming.md'
