# Project information
site_name: DigiDocs
site_description: DigiDocs is a collection of concise tutorials focused on full-stack software engineering and cloud operations.
site_author: Evan Tay
site_url: https://www.evantay.com/docs/

# Repository
repo_name: DigiPie/digidocs
repo_url: https://github.com/DigiPie/digidocs

# Copyright
copyright: Copyright &copy; Evan Tay

# Configuration
theme:
  name: material
  language: en
  highlightjs: true
  feature:
    - tabs
    - instant
  palette:
    scheme: slate
    primary: blue
    accent: blue

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DigiPie
  disqus: digipie-digidocs
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Web Dev:
      - MongoDB:
          - Cheat sheet: mongodb/cheat-sheet.md
          - Local setup: mongodb/local-setup.md
      - NodeJS:
          - Auto reload: nodejs/auto-reload.md
          - Set npm run shell: nodejs/set-npm-run-shell.md
  - Network:
      - Mininet: 
          - Getting started: mininet/getting-started.md
  - Cloud:
      - Google Cloud:
          - Kubernetes Engine: gcp/kubernetes-engine.md
      - Docker: container/docker.md
      - Heroku quick deploy: heroku/quick-deploy.md
      - Ubuntu 18.04: os/ubuntu18-04.md
  - Git:
      - Cheat sheet: git/cheat-sheet.md
      - Ignoring files: git/ignoring-files.md
  - Coding:
      - C:
          - Arguments: c/arguments.md
  - Recommendation list: list.md
