# Project information
site_name: DigiDocs
site_description: 'A MkDocs powered static site for personal note-taking and documentation.'
site_author: 'Evan Tay'
site_url: 'http://digipie.github.io/'

# Repository
repo_name: 'DigiPie/digipie.github.io'
repo_url: 'https://github.com/DigiPie/digipie.github.io'

# Copyright
copyright: 'Copyright &copy; Evan Tay'

# Configuration
theme:
  name: 'material'
  language: 'en'
  custom_dir: 'add'
  highlightjs: true
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/DigiPie'
    - type: 'globe'
      link: 'http://www.evantay.com'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true

nav:
    - Home: index.md
    - Git:
      - Ignoring files: git/ignoring-files.md
